const J=(x,s=200,h={})=>new Response(JSON.stringify(x),{status:s,headers:{"content-type":"application/json;charset=utf-8","cache-control":"no-store","x-content-type-options":"nosniff","referrer-policy":"strict-origin-when-cross-origin",...h}});
const hash=async s=>{const b=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(s));return [...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,"0")).join("")};
const sid=r=>{const m=(r.headers.get("Cookie")||"").match(/(?:^|; )fa_session=([^;]+)/);return m&&decodeURIComponent(m[1])};
const auth=async(r,e)=>{const s=sid(r);return !!(s&&e.SESSIONS&&await e.SESSIONS.get("admin:"+s))};
const settings=async e=>Object.fromEntries((await e.DB.prepare("SELECT key,value FROM settings").all()).results.map(x=>[x.key,x.value]));
async function data(e){const q=async t=>(await e.DB.prepare("SELECT id,title,body,meta,image FROM items WHERE type=? AND published=1 ORDER BY sort_order,id").bind(t).all()).results||[];return{settings:await settings(e),services:await q("service"),projects:await q("project"),timeline:await q("timeline"),reviews:await q("review")}}
const cookie=(v,age)=>`fa_session=${encodeURIComponent(v)}; Path=/; HttpOnly; SameSite=Strict; Max-Age=${age}`;
export default{async fetch(r,e){const u=new URL(r.url);
try{
if(u.pathname==="/api/public"&&r.method==="GET")return J(await data(e));
if(u.pathname==="/api/inquiry"&&r.method==="POST"){const d=await r.json();if(!d.name||!d.phone)return J({error:"نام و شماره تماس الزامی است."},400);await e.DB.prepare("INSERT INTO inquiries(name,phone,message) VALUES(?,?,?)").bind(String(d.name).trim(),String(d.phone).trim(),String(d.message||"")).run();return J({ok:true})}
if(u.pathname==="/api/auth/status")return J({setup:!!(await e.DB.prepare("SELECT id FROM admins WHERE id=1").first()),auth:await auth(r,e)});
if(u.pathname==="/api/auth/setup"&&r.method==="POST"){if(await e.DB.prepare("SELECT id FROM admins WHERE id=1").first())return J({error:"حساب مدیر قبلاً ساخته شده است."},409);const d=await r.json();if(String(d.username||"").length<3||String(d.password||"").length<10)return J({error:"نام کاربری حداقل ۳ و رمز عبور حداقل ۱۰ کاراکتر باشد."},400);await e.DB.prepare("INSERT INTO admins(id,username,password_hash) VALUES(1,?,?)").bind(String(d.username).trim(),await hash(String(d.password))).run();return J({ok:true})}
if(u.pathname==="/api/auth/login"&&r.method==="POST"){const d=await r.json(),a=await e.DB.prepare("SELECT * FROM admins WHERE id=1 AND username=?").bind(String(d.username)).first();if(!a||await hash(String(d.password))!==a.password_hash)return J({error:"نام کاربری یا رمز عبور اشتباه است."},401);const s=crypto.randomUUID();await e.SESSIONS.put("admin:"+s,String(a.username),{expirationTtl:86400});return J({ok:true},200,{"Set-Cookie":cookie(s,86400)})}
if(u.pathname==="/api/auth/logout"&&r.method==="POST"){const s=sid(r);if(s)await e.SESSIONS.delete("admin:"+s);return J({ok:true},200,{"Set-Cookie":cookie("",0)})}
if(u.pathname.startsWith("/api/admin/")){if(!await auth(r,e))return J({error:"Unauthorized"},401);
if(u.pathname==="/api/admin/data")return J({...await data(e),items:(await e.DB.prepare("SELECT * FROM items ORDER BY type,sort_order,id").all()).results||[],inquiries:(await e.DB.prepare("SELECT * FROM inquiries ORDER BY id DESC").all()).results||[]});
if(u.pathname==="/api/admin/settings"&&r.method==="POST"){for(const[k,v]of Object.entries(await r.json()))await e.DB.prepare("INSERT INTO settings(key,value) VALUES(?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value").bind(k,String(v??"")).run();return J({ok:true})}
if(u.pathname==="/api/admin/item"&&r.method==="POST"){const d=await r.json();if(!d.title||!d.type)return J({error:"نوع و عنوان الزامی است."},400);if(Number(d.id))await e.DB.prepare("UPDATE items SET type=?,title=?,body=?,meta=?,image=?,sort_order=?,published=? WHERE id=?").bind(d.type,d.title,d.body||"",d.meta||"",d.image||"",Number(d.sort_order||0),d.published===false?0:1,Number(d.id)).run();else await e.DB.prepare("INSERT INTO items(type,title,body,meta,image,sort_order,published) VALUES(?,?,?,?,?,?,1)").bind(d.type,d.title,d.body||"",d.meta||"",d.image||"",Number(d.sort_order||0)).run();return J({ok:true})}
if(u.pathname==="/api/admin/item/delete"&&r.method==="POST"){await e.DB.prepare("DELETE FROM items WHERE id=?").bind(Number((await r.json()).id)).run();return J({ok:true})}
if(u.pathname==="/api/admin/inquiry/status"&&r.method==="POST"){const d=await r.json();await e.DB.prepare("UPDATE inquiries SET status=? WHERE id=?").bind(d.status||"read",Number(d.id)).run();return J({ok:true})}
if(u.pathname==="/api/admin/password"&&r.method==="POST"){const p=String((await r.json()).password||"");if(p.length<10)return J({error:"رمز حداقل ۱۰ کاراکتر باشد."},400);await e.DB.prepare("UPDATE admins SET password_hash=? WHERE id=1").bind(await hash(p)).run();return J({ok:true})}
}
const res=await e.ASSETS.fetch(r);const h=new Headers(res.headers);h.set("x-content-type-options","nosniff");h.set("referrer-policy","strict-origin-when-cross-origin");h.set("permissions-policy","camera=(), microphone=(), geolocation=()");return new Response(res.body,{status:res.status,statusText:res.statusText,headers:h})}catch(x){return J({error:String(x)},500)}}};